OctoPrint: 5
printers: 5

OctoPrints:
  - port: 5001
    apikey: '9C623DF96CFD45B1A52A634564C73CA6'
  - port: 5002
    apikey: '9C623DF96CFD45B1A52A634564C73CA6'
  - port: 5003
    apikey: '9C623DF96CFD45B1A52A634564C73CA6'
  - port: 5004
    apikey: '9C623DF96CFD45B1A52A634564C73CA6'
  - port: 5005
    apikey: '9C623DF96CFD45B1A52A634564C73CA6'
  - port: 5006
    apikey: '9C623DF96CFD45B1A52A634564C73CA6'
  - port: 5007
    apikey: '9C623DF96CFD45B1A52A634564C73CA6'
  - port: 5008
    apikey: '9C623DF96CFD45B1A52A634564C73CA6'
  - port: 5009
    apikey: '9C623DF96CFD45B1A52A634564C73CA6'
  - port: 5010
    apikey: '9C623DF96CFD45B1A52A634564C73CA6'
  - port: 5011
    apikey: '9C623DF96CFD45B1A52A634564C73CA6'

Printers:
  - name: Emilio
    type: Ender
    serial: a107cbuz
  - name: Ender
    type: Ender
    serial: a107cbgy
  - name: Emma
    type: Ender
    serial: a107cc3j
  - name: Emanuel
    type: Ender
    serial: ah06pb6y
  - name: Esther
    type: Ender
    serial: a107ccd4
  - name: Eggsy
    type: Ender
    serial: ah06pb64
  - name: Eunice
    type: Ender
    serial: a107cbqr
  - name: Eddard
    type: Ender
    serial: ah06piuv
  - name: Eleanor
    type: Ender
    serial: ah06pclw
  - name: Eloise
    type: Ender
    serial: ah06pazg

Profiles:
  - id: Ender
    name: Ender
    heatedBed: false
    volume:
      x: 150
      y: 150
      z: 200
  - id: printrbot-play
    name: printrbot play
    heatedBed: false
    volume:
      x: 200
      y: 200
      z: 200
  - id: printrbot-simple
    name: printrbot simple
    heatedBed: true
    volume:
      x: 200
      y: 200
      z: 200
  - id: printrbot-plus
    name: printrbot simple
    heatedBed: true
    volume:
      x: 200
      y: 200
      z: 200
  - id: robo-3d
    name: printrbot simple
    heatedBed: true
    volume:
      x: 200
      y: 200
      z: 200
